using System.Collections.Generic;

namespace RoR2ProfileManager
{
    public static class DataNameTranslator
    {
        public static Dictionary<string, string> Achievements = new Dictionary<string, string>
        {
            { "Rapidfire" , "AttackSpeed"},
            { "Automation Activation" , "AutomationActivation"},
            { "...To Be Left Alone" , "BeatArena"},
            { "Warm For Life" , "BurnToDeath"},
            { "Moon Worshipper" , "CarryLunarItems"},
            { "Glorious Battle" , "ChargeTeleporterWhileNearDeath"},
            { "Cleanup Duty" , "CleanupDuty"},
            { "Commando: Mastery" , "CommandoClearGameMonsoon"},
            { "Commando: Godspeed" , "CommandoFastFirstStageClear"},
            { "Commando: Rolling Thunder" , "CommandoKillOverloadingWorm"},
            { "Commando: Incorruptible" , "CommandoNonLunarEndurance"},
            { "The Long Road" , "Complete20Stages"},
            { "Engineering Perfection" , "Complete30StagesCareer"},
            { "Ascendant" , "CompleteMultiBossShrine"},
            { "Prismatically Aligned" , "CompletePrismaticTrial"},
            { "Advancement" , "CompleteTeleporter"},
            { "Flawless" , "CompleteTeleporterWithoutInjury"},
            { "Warrior" , "CompleteThreeStages"},
            { "Naturopath" , "CompleteThreeStagesWithoutHealing"},
            { "True Respite" , "CompleteUnknownEnding"},
            { "Acrid: Mastery" , "CrocoClearGameMonsoon"},
            { "Acrid: Bad Medicine" , "CrocoKillScavenger"},
            { "Acrid: Easy Prey" , "CrocoKillWeakEnemiesMilestone"},
            { "Acrid: Pandemic" , "CrocoTotalInfectionsMilestone"},
            { "Guidance Offline" , "DefeatSuperRoboBallBoss"},
            { "Learning Process" , "Die5Times"},
            { "The Basics" , "Discover10UniqueTier1"},
            { "Experimenting" , "Discover5Equipment"},
            { "Engineer: Better With Friends" , "EngiArmy"},
            { "Engineer: Mastery" , "EngiClearGameMonsoon"},
            { "Engineer: Zero Sum" , "EngiClearTeleporterWithZeroMonsters"},
            { "100% Calculated" , "EngiKillBossQuick"},
            { "\"Is This Bugged?\"" , "FailShrineChance"},
            { "Her Concepts" , "FindDevilAltar"},
            { "[REDACTED]" , "FindTimedChest"},
            { "Newtist" , "FindUniqueNewtStatues"},
            { "Pause" , "FreeMage"},
            { "Deicide" , "HardEliteBossKill"},
            { "Macho" , "HardHitter"},
            { "Huntress: Finishing Touch" , "HuntressAllGlaiveBouncesKill"},
            { "Huntress: Mastery" , "HuntressClearGameMonsoon"},
            { "Huntress: One Shot, One Kill" , "HuntressCollectCrowbars"},
            { "Huntress: Piercing Wind" , "HuntressMaintainFullHealthOnFrozenWall"},
            { "Blockade Breaker" , "KillBossQuantityInRun"},
            { "Keyed Up" , "KillBossQuick"},
            { "Death Do Us Part" , "KillElementalLemurians"},
            { "Elite Slayer" , "KillEliteMonster"},
            { "Cut Down" , "KillElitesMilestone"},
            { "Blackout" , "KillGoldTitanInOneCycle"},
            { "Slaughter" , "KillTotalEnemies"},
            { "Loader: Earthshatter" , "LoaderBigSlam"},
            { "Loader: Mastery" , "LoaderClearGameMonsoon"},
            { "Loader: Swing By" , "LoaderSpeedRun"},
            { "Bookworm" , "LogCollector"},
            { "Deja Vu?" , "LoopOnce"},
            { "Artificer: Orbital Bombardment" , "MageAirborneMultiKill"},
            { "Artificer: Mastery" , "MageClearGameMonsoon"},
            { "Artificer: Chunked!" , "MageFastBoss"},
            { "Artificer: Massacre" , "MageMultiKill"},
            { "Multikill!" , "MajorMultikill"},
            { "One with the Woods" , "MaxHealingShrine"},
            { "Mercenary: Mastery" , "MercClearGameMonsoon"},
            { "Mercenary: Ethereal" , "MercCompleteTrialWithFullHealth"},
            { "Mercenary: Demon of the Skies" , "MercDontTouchGround"},
            { "Going Fast Recommended" , "MoveSpeed"},
            { "Warmonger" , "MultiCombatShrine"},
            { "Never Back Down" , "NeverBackDown"},
            { "Trial of Spite" , "ObtainArtifactBomb"},
            { "Trial of Command" , "ObtainArtifactCommand"},
            { "Trial of Honor" , "ObtainArtifactEliteOnly"},
            { "Trial of Enigma" , "ObtainArtifactEnigma"},
            { "Trial of Chaos" , "ObtainArtifactFriendlyFire"},
            { "Trial of Glass" , "ObtainArtifactGlass"},
            { "Trial of Dissonance" , "ObtainArtifactMixEnemy"},
            { "Trial of Evolution" , "ObtainArtifactMonsterTeamGainsItems"},
            { "Trial of Metamorphosis" , "ObtainArtifactRandomSurvivorOnRespawn"},
            { "Trial of Sacrifice" , "ObtainArtifactSacrifice"},
            { "Trial of Vengeance" , "ObtainArtifactShadowClone"},
            { "Trial of Kin" , "ObtainArtifactSingleMonsterType"},
            { "Trial of Swarms" , "ObtainArtifactSwarms"},
            { "Trial of Death" , "ObtainArtifactTeamDeath"},
            { "Trial of Frailty" , "ObtainArtifactWeakAssKnees"},
            { "Trial of Soul" , "ObtainArtifactWispOnDeath"},
            { "...Maybe One More." , "RepeatedlyDuplicateItems"},
            { "Verified" , "RepeatFirstTeleporter"},
            { "Power Plant" , "RescueTreebot"},
            { "The Lone Survivor" , "StayAlive1"},
            { "The Demons And The Crabs" , "SuicideHermitCrabs"},
            { "MUL-T: Mastery" , "ToolbotClearGameMonsoon"},
            { "MUL-T: Pest Control" , "ToolbotGuardTeleporter"},
            { "MUL-T: gotcha" , "ToolbotKillImpBossWithBfg"},
            { "MUL-T: Gotcha" , "ToolbotKillImpBossWithBFG"},
            { "Mechanic" , "TotalDronesRepaired"},
            { "Funded!" , "TotalMoneyCollected"},
            { "REX: Mastery" , "TreebotClearGameMonsoon"},
            { "REX: Dunked" , "TreebotDunkClayBoss"},
            { "REX: Bushwhacked" , "TreebotLowHealthTeleporter"},
            { "Cosmic Explorer" , "UseThreePortals"}

        };

        /*public static Dictionary<string, string> DiscoveredPickups = new Dictionary<string, string>
        {
            { "" , "ArtifactIndex.Bomb"},
            { "" , "ArtifactIndex.Command"},
            { "" , "ArtifactIndex.EliteOnly"},
            { "" , "ArtifactIndex.Enigma"},
            { "" , "ArtifactIndex.FriendlyFire"},
            { "" , "ArtifactIndex.Glass"},
            { "" , "ArtifactIndex.MixEnemy"},
            { "" , "ArtifactIndex.MonsterTeamGainsItems"},
            { "" , "ArtifactIndex.RandomSurvivorOnRespawn"},
            { "" , "ArtifactIndex.Sacrifice"},
            { "" , "ArtifactIndex.ShadowClone"},
            { "" , "ArtifactIndex.SingleMonsterType"},
            { "" , "ArtifactIndex.Swarms"},
            { "" , "ArtifactIndex.WeakAssKnees"},
            { "" , "ArtifactIndex.WispOnDeath"},
            { "" , "EquipmentIndex.AffixBlue"},
            { "" , "EquipmentIndex.AffixHaunted"},
            { "" , "EquipmentIndex.AffixPoison"},
            { "" , "EquipmentIndex.AffixRed"},
            { "" , "EquipmentIndex.AffixWhite"},
            { "" , "EquipmentIndex.BFG"},
            { "" , "EquipmentIndex.Blackhole"},
            { "" , "EquipmentIndex.BurnNearby"},
            { "" , "EquipmentIndex.Cleanse"},
            { "" , "EquipmentIndex.CommandMissile"},
            { "" , "EquipmentIndex.CrippleWard"},
            { "" , "EquipmentIndex.CritOnUse"},
            { "" , "EquipmentIndex.DroneBackup"},
            { "" , "EquipmentIndex.FireBallDash"},
            { "" , "EquipmentIndex.Fruit"},
            { "" , "EquipmentIndex.GainArmor"},
            { "" , "EquipmentIndex.Gateway"},
            { "" , "EquipmentIndex.GoldGat"},
            { "" , "EquipmentIndex.Jetpack"},
            { "" , "EquipmentIndex.Lightning"},
            { "" , "EquipmentIndex.Meteor"},
            { "" , "EquipmentIndex.PassiveHealing"},
            { "" , "EquipmentIndex.QuestVolatileBattery"},
            { "" , "EquipmentIndex.Recycle"},
            { "" , "EquipmentIndex.Saw"},
            { "" , "EquipmentIndex.Scanner"},
            { "" , "EquipmentIndex.Tonic"},
            { "" , "ItemIndex.AlienHead"},
            { "" , "ItemIndex.ArmorPlate"},
            { "" , "ItemIndex.ArmorReductionOnHit"},
            { "" , "ItemIndex.ArtifactKey"},
            { "" , "ItemIndex.AttackSpeedOnCrit"},
            { "" , "ItemIndex.AutoCastEquipment"},
            { "" , "ItemIndex.Bandolier"},
            { "" , "ItemIndex.BarrierOnKill"},
            { "" , "ItemIndex.BarrierOnOverHeal"},
            { "" , "ItemIndex.Bear"},
            { "" , "ItemIndex.BeetleGland"},
            { "" , "ItemIndex.Behemoth"},
            { "" , "ItemIndex.BleedOnHit"},
            { "" , "ItemIndex.BonusGoldPackOnKill"},
            { "" , "ItemIndex.BossDamageBonus"},
            { "" , "ItemIndex.BounceNearby"},
            { "" , "ItemIndex.ChainLightning"},
            { "" , "ItemIndex.Clover"},
            { "" , "ItemIndex.CritGlasses"},
            { "" , "ItemIndex.Crowbar"},
            { "" , "ItemIndex.Dagger"},
            { "" , "ItemIndex.DeathMark"},
            { "" , "ItemIndex.EnergizedOnEquipmentUse"},
            { "" , "ItemIndex.EquipmentMagazine"},
            { "" , "ItemIndex.ExecuteLowHealthElite"},
            { "" , "ItemIndex.ExplodeOnDeath"},
            { "" , "ItemIndex.ExtraLife"},
            { "" , "ItemIndex.FallBoots"},
            { "" , "ItemIndex.Feather"},
            { "" , "ItemIndex.FireRing"},
            { "" , "ItemIndex.Firework"},
            { "" , "ItemIndex.FocusConvergence"},
            { "" , "ItemIndex.GhostOnKill"},
            { "" , "ItemIndex.GoldOnHit"},
            { "" , "ItemIndex.HeadHunter"},
            { "" , "ItemIndex.HealOnCrit"},
            { "" , "ItemIndex.HealWhileSafe"},
            { "" , "ItemIndex.Hoof"},
            { "" , "ItemIndex.IceRing"},
            { "" , "ItemIndex.Icicle"},
            { "" , "ItemIndex.IgniteOnKill"},
            { "" , "ItemIndex.IncreaseHealing"},
            { "" , "ItemIndex.Infusion"},
            { "" , "ItemIndex.JumpBoost"},
            { "" , "ItemIndex.KillEliteFrenzy"},
            { "" , "ItemIndex.Knurl"},
            { "" , "ItemIndex.LaserTurbine"},
            { "" , "ItemIndex.LunarDagger"},
            { "" , "ItemIndex.LunarPrimaryReplacement"},
            { "" , "ItemIndex.LunarTrinket"},
            { "" , "ItemIndex.LunarUtilityReplacement"},
            { "" , "ItemIndex.Medkit"},
            { "" , "ItemIndex.Missile"},
            { "" , "ItemIndex.Mushroom"},
            { "" , "ItemIndex.NearbyDamageBonus"},
            { "" , "ItemIndex.NovaOnHeal"},
            { "" , "ItemIndex.NovaOnLowHealth"},
            { "" , "ItemIndex.Pearl"},
            { "" , "ItemIndex.PersonalShield"},
            { "" , "ItemIndex.Phasing"},
            { "" , "ItemIndex.Plant"},
            { "" , "ItemIndex.RegenOnKill"},
            { "" , "ItemIndex.RepeatHeal"},
            { "" , "ItemIndex.SecondarySkillMagazine"},
            { "" , "ItemIndex.Seed"},
            { "" , "ItemIndex.ShieldOnly"},
            { "" , "ItemIndex.ShinyPearl"},
            { "" , "ItemIndex.ShockNearby"},
            { "" , "ItemIndex.SlowOnHit"},
            { "" , "ItemIndex.SprintArmor"},
            { "" , "ItemIndex.SprintBonus"},
            { "" , "ItemIndex.SprintOutOfCombat"},
            { "" , "ItemIndex.SprintWisp"},
            { "" , "ItemIndex.Squid"},
            { "" , "ItemIndex.StickyBomb"},
            { "" , "ItemIndex.StunChanceOnHit"},
            { "" , "ItemIndex.Syringe"},
            { "" , "ItemIndex.Talisman"},
            { "" , "ItemIndex.Thorns"},
            { "" , "ItemIndex.TitanGoldDuringTP"},
            { "" , "ItemIndex.Tooth"},
            { "" , "ItemIndex.TPHealingNova"},
            { "" , "ItemIndex.TreasureCache"},
            { "" , "ItemIndex.UtilitySkillMagazine"},
            { "" , "ItemIndex.WarCryOnMultiKill"},
            { "" , "ItemIndex.WardOnLevel"},
            { "" , "LunarCoin.Coin0"}
        };*/

        public static Dictionary<string, string> Unlocks = new Dictionary<string, string>
        {
            { "Artifact of Spite", "Artifacts.Bomb" },
            { "Artifact of Command", "Artifacts.Command" },
            { "Artifact of Honor", "Artifacts.EliteOnly" },
            { "Artifact of Enigma", "Artifacts.Enigma" },
            { "Artifact of Chaos", "Artifacts.FriendlyFire" },
            { "Artifact of Glass", "Artifacts.Glass" },
            { "Artifact of Dissonance", "Artifacts.MixEnemy" },
            { "Artifact of Evolution", "Artifacts.MonsterTeamGainsItems" },
            { "Artifact of Metamorphosis", "Artifacts.RandomSurvivorOnRespawn" },
            { "Artifact of Sacrifice", "Artifacts.Sacrifice" },
            { "Artifact of Vengance", "Artifacts.ShadowClone" },
            { "Artifact of Kin", "Artifacts.SingleMonsterType" },
            { "Artifact of Swarms", "Artifacts.Swarms" },
            { "Artifact of Death", "Artifacts.TeamDeath" },
            { "Artifact of Frailty", "Artifacts.WeakAssKnees" },
            { "Artifact of Soul", "Artifacts.WispOnDeath" },
            { "Acrid", "Characters.Croco" },
            { "Engineer", "Characters.Engineer" },
            { "Huntress", "Characters.Huntress" },
            { "Loader", "Characters.Loader" },
            { "Artificer", "Characters.Mage" },
            { "Mercenary", "Characters.Mercenary" },
            { "Mul-T", "Characters.Toolbot" },
            { "REX", "Characters.Treebot" },
            { "Predatory Instincts", "Items.AttackSpeedOnCrit" },
            { "Gesture of the Drowned", "Items.AutoCastEquipment" },
            { "Tougher Times", "Items.Bear" },
            { "Preon Accumulator", "Items.BFG" },
            { "Armor-Piercing Rounds", "Items.BossDamageBonus" },
            { "Sentient Meathook", "Items.BounceNearby" },
            { "Hellfire Tincture", "Items.BurnNearby" },
            { "Blast Shower", "Items.Cleanse" },
            { "57 Leaf Clover", "Items.Clover" },
            { "Crowbar", "Items.Crowbar" },
            { "The Back-up", "Items.DroneBackup" },
            { "Kjaro's and Runald's Bands", "Items.ElementalRings" },
            { "War Horn", "Items.EnergizedOnEquipmentUse" },
            { "Fuel Cell", "Items.EquipmentMagazine" },
            { "Old Guillotine", "Items.ExecuteLowHealthElite" },
            { "Dio's Best Friend", "Items.ExtraLife" },
            { "Bundle of Fireworks", "Items.Firework" },
            { "Focused Convergence", "Items.FocusConvergence" },
            { "Eccentric Vase", "Items.Gateway" },
            { "Crowdfunder", "Items.GoldGat" },
            { "Harvester's Scythe", "Items.HealOnCrit" },
            { "Paul's Goat Hoof", "Items.Hoof" },
            { "Rejuvination Rack", "Items.IncreaseHealing" },
            { "Infusion", "Items.Infusion" },
            { "Wax Quail", "Items.JumpBoost" },
            { "Brainstalks", "Items.KillEliteFrenzy" },
            { "Royal Capacitor", "Items.Lightning" },
            { "Heresy Items", "Items.LunarSkillReplacements" },
            { "Medkit", "Items.Medkit" },
            { "Glowing Meteorite", "Items.Meteor" },
            { "Genesis Loop", "Items.NovaOnHeal" },
            { "Gnarled Woodsprite", "Items.PassiveHealing" },
            { "Recycler", "Items.Recycle" },
            { "Radar Scanner", "Items.Scanner" },
            { "Backup Magazine", "Items.SecondarySkillMagazine" },
            { "Unstable Tesla Coil", "Items.ShockNearby" },
            { "Squid Polyp", "Items.Squid" },
            { "Soulbound Catalyst", "Items.Talisman" },
            { "Spinel Tonic", "Items.Tonic" },
            { "Rusted Key", "Items.TreasureCache" },
            { "Berzerker's Pauldrone", "Items.WarCryOnMultiKill" },
            { "Beetle Log", "Logs.BeetleBody.0" },
            { "Beetle Guard Log", "Logs.BeetleGuardBody.0" },
            { "Queen Beetle Log", "Logs.BeetleQueenBody.0" },
            { "Brass Contraption Log", "Logs.BellBody.0" },
            { "Bison Log", "Logs.BisonBody.0" },
            { "Clay Dunestrider Log", "Logs.ClayBossBody.0" },
            { "Clay Templar Log", "Logs.ClayBruiserBody.0" },
            { "Overloading Worm Log", "Logs.ElectricWormBody.0" },
            { "Stone Golem Log", "Logs.GolemBody.0" },
            { "Grovetender Log", "Logs.GravekeeperBody.0" },
            { "Greater Wisp Log", "Logs.GreaterWispBody.0" },
            { "Hermit Crab Log", "Logs.HermitCrabBody.0" },
            { "Imp Log", "Logs.ImpBody.0" },
            { "Imp Overlord Log", "Logs.ImpBossBody.0" },
            { "Jellyfish Log", "Logs.JellyfishBody.0" },
            { "Lumerian Log", "Logs.LemurianBody.0" },
            { "Elder Lumerian Log", "Logs.LemurianBruiserBody.0" },
            { "Magma Worm Log", "Logs.MagmaWormBody.0" },
            { "Mini Mushroom Log", "Logs.MiniMushroom.0" },
            { "Void Reaver Log", "Logs.Nullifier.0" },
            { "Parent Log", "Logs.Parent.0" },
            { "Solus Control Unit Log", "Logs.RoboBallBossBody.0" },
            { "Solus Probe Log", "Logs.RoboBallMiniBody.0" },
            { "Scavenger Log", "Logs.Scav.0" },
            { "Void Fields Log", "Logs.Stages.arena" },
            { "Bulwark's Ambry Log", "Logs.Stages.artifactworld" },
            { "Bazaar Between Time Log", "Logs.Stages.bazaar" },
            { "Distant Roost Log", "Logs.Stages.blackbeach" },
            { "Abyssal Depths Log", "Logs.Stages.dampcavesimple" },
            { "Wetland Aspect Log", "Logs.Stages.foggyswamp" },
            { "Rallypoint Delta Log", "Logs.Stages.frozenwall" },
            { "Gilded Coast Log", "Logs.Stages.goldshores" },
            { "Titanic Plains Log", "Logs.Stages.golemplains" },
            { "Abandoned Aqueduct Log", "Logs.Stages.goolake" },
            { "A Moment Whole Log", "Logs.Stages.limbo" },
            { "A Moment Fractured Log", "Logs.Stages.mysteryspace" },
            { "Siren's Call Log", "Logs.Stages.shipgraveyard" },
            { "Sky Meadow Log", "Logs.Stages.skymeadow" },
            { "Scorched Acres", "Logs.Stages.wispgraveyard" },
            { "Alloy Worship Unit Log", "Logs.SuperRoboBallBossBody.0" },
            { "Stone Titan Log", "Logs.TitanBody.0" },
            { "Aurelionite Log", "Logs.TitanGoldBody.0" },
            { "Wandering Vagrant Log", "Logs.VagrantBody.0" },
            { "Alloy Vulture Log", "Logs.VultureBody.0" },
            { "Lesser Wisp Log", "Logs.WispBody.0" },
            { "Distant Roost Newt Alter 1", "NewtStatue.blackbeach.1" },
            { "Distant Roost Newt Alter 2", "NewtStatue.blackbeach2.0" },
            { "Distant Roost Newt Alter 3", "NewtStatue.blackbeach2.1" },
            { "Distant Roost Newt Alter 4", "NewtStatue.blackbeach2.2" },
            { "Abyssal Depths Newt Alter", "NewtStatue.dampcavesimple.0" },
            { "Wetland Aspect Newt Alter 1", "NewtStatue.foggyswamp.0" },
            { "Wetland Aspect Newt Alter 2", "NewtStatue.foggyswamp.1" },
            { "Wetland Aspcet Newt Alter 3", "NewtStatue.foggyswamp.2" },
            { "Rallypoint Delta Newt Alter 1", "NewtStatue.frozenwall.0" },
            { "Rallypoint Delta Newt Alter 2", "NewtStatue.frozenwall.1" },
            { "Rallypoint Delta Newt Alter 3", "NewtStatue.frozenwall.2" },
            { "Titanic Plains Newt Alter 1", "NewtStatue.golemplains.0" },
            { "Titanic Plains Newt Alter 2", "NewtStatue.golemplains.1" },
            { "Titanic Plains Newt Alter 3", "NewtStatue.golemplains.2" },
            { "Titanic Plains Newt Alter 4", "NewtStatue.golemplains2.0" },
            { "Titanic Plains Newt Alter 5", "NewtStatue.golemplains2.1" },
            { "Titanic Plains Newt Alter 6", "NewtStatue.golemplains2.2" },
            { "Abandoned Aqueduct Newt Alter 1", "NewtStatue.goolake.0" },
            { "Abandoned Aqueduct Newt Alter 2", "NewtStatue.goolake.2" },
            { "Siren's Call Newt Alter 1", "NewtStatue.shipgraveyard.0" },
            { "Siren's Call Newt Alter 2", "NewtStatue.shipgraveyard.2" },
            { "Sky Meadow Newt Alter 1", "NewtStatue.skymeadow.0" },
            { "Sky Meadow Newt Alter 2", "NewtStatue.skymeadow.1" },
            { "Sky Meadow Newt Alter 3", "NewtStatue.skymeadow.2" },
            { "Sky Meadow Newt Alter 4", "NewtStatue.skymeadow.3" },
            { "Sky Meadow Newt Alter 5", "NewtStatue.skymeadow.4" },
            { "Scorched Acres Newt Alter 1", "NewtStatue.wispgraveyard.0" },
            { "Scorched Acres Newt Alter 2", "NewtStatue.wispgraveyard.1" },
            { "Scorched Acres Newt Alter 3", "NewtStatue.wispgraveyard.2" },
            { "Commando Phase Blast", "Skills.Commando.FireShotgunBlast" },
            { "Commando Tactical Slide", "Skills.Commando.SlideJet" },
            { "Commando Frag Grenade", "Skills.Commando.ThrowGrenade" },
            { "Acrid Frenzied Leap", "Skills.Croco.ChainableLeap" },
            { "Acrid Ravenous Bite", "Skills.Croco.CrocoBite" },
            { "Acrid Blight", "Skills.Croco.PassivePoisonLethal" },
            { "Engineer Thermal Harpoons", "Skills.Engi.Harpoon" },
            { "Engineer Spider Mines", "Skills.Engi.SpiderMine" },
            { "Engineer TR58 Carbonizer Turret", "Skills.Engi.WalkerTurret" },
            { "Huntress Flurry", "Skills.Huntress.FlurryArrow" },
            { "Huntress Phase Blink", "Skills.Huntress.MiniBlink" },
            { "Huntress Ballista", "Skills.Huntress.Snipe" },
            { "Loader Spiked Fist", "Skills.Loader.YankHook" },
            { "Loader Thunder Gauntlet", "Skills.Loader.ZapFist" },
            { "Artificer Ion Surge", "Skills.Mage.FlyUp" },
            { "Artificer Cast Nano Spear", "Skills.Mage.IceBomb" },
            { "Artificer Plasma Bolt", "Skills.Mage.LightningBolt" },
            { "Mercenary Eviscerate", "Skills.Merc.EvisProjectile" },
            { "Mercenary Rising Thunder", "Skills.Merc.Uppercut" },
            { "Mul-T Power-Saw", "Skills.Toolbot.Buzzsaw" },
            { "Mult-T Scrap Launcher", "Skills.Toolbot.Grenade" },
            { "REX Seed Barrage", "Skills.Treebot.Barrage" },
            { "REX Bramble Volley", "Skills.Treebot.PlantSonicBoom" },
            { "Commando Alt Skin", "Skins.Commando.Alt1" },
            { "Acrid Alt Skin", "Skins.Croco.Alt1" },
            { "Engineer Alt Skin", "Skins.Engi.Alt1" },
            { "Huntress Alt Skin", "Skins.Huntress.Alt1" },
            { "Loader Alt Skin", "Skins.Loader.Alt1" },
            { "Artificer Alt Skin", "Skins.Mage.Alt1" },
            { "Mercenary Alt Skin", "Skins.Merc.Alt1" },
            { "Mul-T Alt Skin", "Skins.Toolbot.Alt1" },
            { "REX Alt Skin", "Skins.Treebot.Alt1" },

            /*{ "Characters.Croco", "Acrid" },
            { "Characters.Engineer", "Engineer" },
            { "Characters.Huntress", "Huntress" },
            { "Characters.Loader", "Loader" },
            { "Characters.Mage", "Artificer" },
            { "Characters.Mercenary", "Mercenary" },
            { "Characters.Toolbot", "Mul-T" },
            { "Characters.Treebot", "REX" },
            { "Items.AttackSpeedOnCrit", "Predatory Instincts" },
            { "Items.AutoCastEquipment", "Gesture of the Drowned" },
            { "Items.Bear", "Tougher Times" },
            { "Items.BFG", "Preon Accumulator" },
            { "Items.BossDamageBonus", "Armor-Piercing Rounds" },
            { "Items.BounceNearby", "Sentient Meathook" },
            { "Items.BurnNearby", "Hellfire Tincture" },
            { "Items.Cleanse", "Blast Shower" },
            { "Items.Clover", "57 Leaf Clover" },
            { "Items.Crowbar", "Crowbar" },
            { "Items.DroneBackup", "The Back-up" },
            { "Items.ElementalRings", "Kjaro's and Runald's Bands" },
            { "Items.EnergizedOnEquipmentUse", "War Horn" },
            { "Items.EquipmentMagazine", "Fuel Cell" },
            { "Items.ExecuteLowHealthElite", "Old Guillotine" },
            { "Items.ExtraLife", "Dio's Best Friend" },
            { "Items.Gateway", "Eccentric Vase" },
            { "Items.GoldGat", "Crowdfunder" },
            { "Items.Firework", "Bundle of Fireworks" },
            { "Items.Hoof", "Paul's Goat Hoof" },
            { "Items.IncreaseHealing", "Rejuvination Rack" },
            { "Items.HealOnCrit", "Harvester's Scythe" },
            { "Items.Infusion", "Infusion" },
            { "Items.JumpBoost", "Wax Quail" },
            { "Items.KillEliteFrenzy", "Brainstalks" },
            { "Items.Lightning", "Royal Capacitor" },
            { "Items.LunarSkillReplacements", "Heresy Items" },
            { "Items.Medkit", "Medkit" },
            { "Items.Meteor", "Glowing Meteorite" },
            { "Items.NovaOnHeal", "Genesis Loop" },
            { "Items.PassiveHealing", "Gnarled Woodsprite" },
            { "Items.Scanner", "Radar Scanner" },
            { "Items.SecondarySkillMagazine", "Backup Magazine" },
            { "Items.ShockNearby", "Unstable Tesla Coil" },
            { "Items.Talisman", "Soulbound Catalyst" },
            { "Items.Tonic", "Spinel Tonic" },
            { "Items.TreasureCache", "Rusted Key" },
            { "Items.WarCryOnMultiKill", "Berzerker's Pauldrone" },
            { "Logs.BeetleBody.0", "Beetle Log" },
            { "Logs.BeetleGuardBody.0", "Beetle Guard Log" },
            {"Logs.BeetleQueenBody.0", "Queen Beetle Log" },
            { "Logs.BellBody.0", "Brass Contraption Log" },
            { "Logs.BisonBody.0", "Bison Log" },
            { "Logs.ClayBossBody.0", "Clay Dunestrider Log" },
            { "Logs.ClayBruiserBody.0", "Clay Templar Log" },
            { "Logs.GolemBody.0", "Stone Golem Log" },
            { "Logs.GravekeeperBody.0", "Grovetender Log" },
            { "Logs.GreaterWispBody.0", "Greater Wisp Log" },
            { "Logs.HermitCrabBody.0", "Hermit Crab Log" },
            { "Logs.ImpBody.0", "Imp Log" },
            { "Logs.ImpBossBody.0", "Imp Overlord Log" },
            { "Logs.JellyfishBody.0", "Jellyfish Log" },
            { "Logs.LemurianBody.0", "Lumerian Log" },
            { "Logs.LemurianBruiserBody.0", "Elder Lumerian Log" },
            { "Logs.MagmaWormBody.0", "Magma Worm Log" },
            { "Logs.Nullifier.0", "Void Reaver Log" },
            { "Logs.RoboBallMiniBody.0", "Solus Probe Log" },
            { "Logs.Scav.0", "Scavenger Log" },
            { "Logs.Stages.arena", "Void Fields Log" },
            { "Logs.Stages.bazaar", "Bazaar Between Time Log" },
            { "Logs.Stages.blackbeach", "Distant Roost Log" },
            { "Logs.Stages.dampcavesimple", "Abyssal Depths Log" },
            { "Logs.Stages.foggyswamp", "Wetland Aspect Log" },
            { "Logs.Stages.frozenwall", "Rallypoint Delta Log" },
            { "Logs.Stages.goldshores", "Gilded Coast Log" },
            { "Logs.Stages.golemplains", "Titanic Plains Log" },
            { "Logs.Stages.goolake", "Abandoned Aqueduct Log" },
            { "Logs.Stages.limbo", "A Moment Whole Log" },
            { "Logs.Stages.mysteryspace", "A Moment Fractured Log" },
            { "Logs.Stages.shipgraveyard", "Siren's Call Log" },
            { "Logs.Stages.wispgraveyard", "Scorched Acres" },
            { "Logs.SuperRoboBallBossBody.0", "Solus Control Unit Log" },
            { "Logs.TitanBody.0", "Stone Titan Log" },
            { "Logs.VagrantBody.0", "Wandering Vagrant Log" },
            { "Logs.VultureBody.0", "Alloy Vulture Log" },
            { "Logs.WispBody.0", "Lesser Wisp Log" },
            { "NewtStatue.blackbeach2.1", "Distant Roost Newt Alter 1" },
            { "NewtStatue.blackbeach2.2", "Distant Roost Newt Alter 2" },
            { "NewtStatue.dampcavesimple.0", "Abyssal Depths Newt Alter" },
            { "NewtStatue.foggyswamp.0", "Wetland Aspect Newt Alter 1" },
            { "NewtStatue.foggyswamp.1", "Wetland Aspect Newt Alter 2" },
            { "NewtStatue.foggyswamp.2", "Wetland Aspcet Newt Alter 3" },
            { "NewtStatue.frozenwall.0", "Rallypoint Delta Newt Alter 1" },
            { "NewtStatue.frozenwall.1", "Rallypoint Delta Newt Alter 2" },
            { "NewtStatue.frozenwall.2", "Rallypoint Delta Newt Alter 3" },
            { "NewtStatue.golemplains.1", "Titanic Plains Newt Alter 1" },
            { "NewtStatue.golemplains2.0", "Titanic Plains Newt Alter 2" },
            { "NewtStatue.golemplains2.1", "Titanic Plains Newt Alter 3" },
            { "NewtStatue.golemplains2.2", "Titanic Plains Newt Alter 4" },
            { "NewtStatue.goolake.0", "Abandoned Aqueduct Newt Alter 1" },
            { "NewtStatue.goolake.2", "Abandoned Aqueduct Newt Alter 2" },
            { "NewtStatue.shipgraveyard.0", "Siren's Call Newt Alter 1" },
            { "NewtStatue.shipgraveyard.2", "Siren's Call Newt Alter 2" },
            { "NewtStatue.wispgraveyard.0", "Scorched Acres Newt Alter 1" },
            { "NewtStatue.wispgraveyard.1", "Scorched Acres Newt Alter 2" },
            { "Skills.Commando.FireShotgunBlast", "Commando Phase Blast" },
            { "Skills.Commando.ThrowGrenade", "Commando Frag Grenade" },
            { "Skills.Croco.ChainableLeap", "Acrid Frenzied Leap" },
            { "Skills.Engi.SpiderMine", "Engineer Spider Mines" },
            { "Skills.Engi.WalkerTurret", "Engineer TR58 Carbonizer Turret" },
            { "Skills.Huntress.MiniBlink", "Huntress Phase Blink" },
            { "Skills.Huntress.Snipe", "Huntress Ballista" },
            { "Skills.Loader.YankHook", "Loader Spiked Fist" },
            { "Skills.Loader.ZapFist", "Loader Thunder Gauntlet" },
            { "Skills.Mage.FlyUp", "Artificer Ion Surge" },
            { "Skills.Mage.IceBomb", "Artificer Cast Nano Spear" },
            { "Skills.Mage.LightningBolt", "Artificer Plasma Bolt" },
            { "Skills.Merc.EvisProjectile", "Mercenary Eviscerate" },
            { "Skills.Merc.Uppercut", "Mercenary Rising Thunder" },
            { "Skills.Toolbot.Buzzsaw", "Mul-T Power-Saw" },
            { "Skills.Toolbot.Grenade","Mult-T Scrap Launcher" },
            { "Skills.Treebot.Barrage", "REX Seed Barrage" },
            { "Skills.Treebot.PlantSonicBoom", "REX Bramble Volley"},
            { "Skins.Commando.Alt1", "Commando Alt Skin" },
            { "Skins.Croco.Alt1", "Acrid Alt Skin" },
            { "Skins.Huntress.Alt1", "Huntress Alt Skin" },
            { "Skins.Loader.Alt1", "Loader Alt Skin" },
            { "Skins.Mage.Alt1", "Artificer Alt Skin" },
            { "Skins.Merc.Alt1", "Mercenary Alt Skin" },
            { "Skins.Toolbot.Alt1", "Mul-T Alt Skin"},
            { "Skins.Treebot.Alt1", "REX Alt Skin" }*/
        };
    }
}
